# docker-compose.yml
version: '3.1'
services:
  db:
    user: 1000:1000
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: college
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
